# Generated by Django 5.2.17 on 2026-08-20 13:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contacts', '0001_initial'),
        ('integrations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='integration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='integrations.integration'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['integration', 'external_id'], name='contacts_integra_dc8ac9_idx'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['name'], name='contacts_name_084782_idx'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['phone'], name='contacts_phone_3b79d2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='contact',
            unique_together={('integration', 'external_id')},
        ),
    ]
