# Generated by Django 5.2.17 on 2026-08-20 13:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('conversations', '0001_initial'),
        ('integrations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='integration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='integrations.integration'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['integration', 'external_chat_id'], name='conversatio_integra_10160a_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['status'], name='conversatio_status_742c74_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['-last_message_at'], name='conversatio_last_me_99c95c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='conversation',
            unique_together={('integration', 'external_chat_id')},
        ),
    ]
