# Generated by Django 5.2.17 on 2026-08-22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conversations", "0003_conversation_external_peer_data"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="conversation",
            name="is_pinned",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name="conversation",
            name="priority",
            field=models.CharField(
                choices=[
                    ("low", "Low"),
                    ("normal", "Normal"),
                    ("high", "High"),
                    ("urgent", "Urgent"),
                ],
                db_index=True,
                default="normal",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="conversation",
            name="snoozed_until",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="ConversationNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conversation_notes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notes",
                        to="conversations.conversation",
                    ),
                ),
            ],
            options={
                "db_table": "conversation_notes",
                "ordering": ["-created_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["conversation", "-created_at"],
                        name="conversatio_convers_a97cdb_idx",
                    ),
                    models.Index(
                        fields=["author"],
                        name="conversatio_author__ba0480_idx",
                    ),
                ],
            },
        ),
    ]
