# Generated by Django 5.2.17 on 2026-08-21 09:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='integrationevent',
            constraint=models.UniqueConstraint(condition=models.Q(('external_event_id', ''), _negated=True), fields=('integration', 'external_event_id'), name='unique_integration_external_event'),
        ),
    ]
