# Generated by Django 5.2.17 on 2026-08-20 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Integration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('telegram', 'Telegram'), ('whatsapp', 'WhatsApp')], max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('error', 'Error'), ('pending', 'Pending')], default='pending', max_length=20)),
                ('external_account_id', models.CharField(blank=True, max_length=255)),
                ('credentials', models.JSONField(blank=True, default=dict)),
                ('webhook_url', models.URLField(blank=True)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'integrations',
                'ordering': ['-created_at'],
            },
        ),
    ]
