# Generated by Django 5.2.17 on 2026-08-20 13:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('integrations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='integration',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integrations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='integration',
            index=models.Index(fields=['user', 'platform'], name='integration_user_id_5efdb8_idx'),
        ),
        migrations.AddIndex(
            model_name='integration',
            index=models.Index(fields=['status'], name='integration_status_7ea6a9_idx'),
        ),
    ]
