# Generated by Django 5.2.17 on 2026-08-21 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='integration',
            name='last_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='integration',
            name='session_data',
            field=models.TextField(blank=True),
        ),
    ]
