# Generated by Django 5.2.17 on 2026-08-22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("integrations", "0003_integration_last_error_integration_session_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="integration",
            name="platform",
            field=models.CharField(
                choices=[
                    ("telegram", "Telegram"),
                    ("whatsapp", "WhatsApp"),
                    ("instagram", "Instagram"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddConstraint(
            model_name="integration",
            constraint=models.UniqueConstraint(
                condition=(
                    models.Q(platform="instagram", status="active")
                    & ~models.Q(external_account_id="")
                ),
                fields=("external_account_id",),
                name="uniq_active_instagram_account",
            ),
        ),
    ]
