# Generated by Django 5.2.17 on 2026-08-24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("integrations", "0004_instagram_platform_and_unique_account"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="integration",
            name="platform",
            field=models.CharField(
                choices=[
                    ("telegram", "Telegram"),
                    ("whatsapp", "WhatsApp"),
                    ("instagram", "Instagram"),
                    ("facebook", "Facebook"),
                    ("viber", "Viber"),
                    ("vk", "VK"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddConstraint(
            model_name="integration",
            constraint=models.UniqueConstraint(
                condition=(
                    models.Q(platform="facebook", status="active")
                    & ~models.Q(external_account_id="")
                ),
                fields=("external_account_id",),
                name="uniq_active_facebook_account",
            ),
        ),
    ]
