# Generated by Django 5.2.17 on 2026-08-21 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('new_message', 'New Message'), ('message_failed', 'Message Failed'), ('new_order', 'New Order'), ('integration_error', 'Integration Error'), ('system', 'System')], max_length=20),
        ),
    ]
